  export const Colors = {
  BRAND: "#0086A8",
  BRAND_DARK: "#007693",
  BRAND_DARKEST: "#00657E",

  TEXT_PRIMARY: "#353238",
  TEXT_SECONDARY: "#828282",
  TEXT_LIGHT: "#FFFFFF",
  TEXT_SUP: "#CCC",
  TEXT_DISABLED: "#E3E3E3",
  TEXT_PLACEHOLDER: "#E3E3E3",

  HOVER: "#FAFAFA",
  HOVER_TEXT: "#555",

  BACKGROUND_GREEN:  "#5FD975",
  BACKGROUND_ACTIVE: "#FAFAFA",

  BORDER_PRIMARY: "#E3E3E3",

  /* UNIQUE */
  BACKGROUND_CATALOG_ITEM: "#F7F7F7",
  BACKGROUND_ACTIVE_FILTER_ITEM: "#F5F5F5",
  BACKGROUND_BUTTON_TOGGLE: "#E3E3E3",
  BACKGROUND_RANGE_SLIDER: "#E3E3E3",
  BACKGROUND_FABRICS_SAMPLES: "#E3E3E3",
}